### ISSUE TITLE
docker-compose文件ldap配置问题

### ISSUE THREAD

**Issue by allen7593** [longguikeji/arkid-charts#25]
arkid-charts-v2
docker-compose文件ldap配置问题
https://github.com/longguikeji/arkid-charts/blob/a63550cd683643552e576aedd9aabd88963a0e5e/docker-compose/docker-compose.yml#L73
73行应该为：
      - BACKEND=db
而不是
      - BACKEND=sql
否则会导致ldap无法启动并产生如下错误
backend_startup_one (type=sql, suffix="dc=example,dc=org"): bi_db_open failed! (1)

**Comment by notevery** [comment]
@allen7593 哈喽，谢谢提issue！这个配置是没有问题的，`BACKEND=sql` 代表使用mysql作为ldap的后端存储（仅在此镜像中）。启动的错误可能是异常退出导致的，可以尝试重启：`docker-compose down && docker-compose up -d`
![image](https://user-images.githubusercontent.com/12843847/146886868-ce7106c7-8e04-4f48-b540-a188cc6933f9.png)
